name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7

      - name: Install dependecies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
        
