name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node command
        default: node runner.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.15.1-chrome-126.0.6478.114-1-ff-128.0-edge-126.0.2592.61-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7

      - name: Install dependecies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
        
